server:
  port: 8080

spring:
  application:
    name: stock
  datasource:
    url: jdbc:mysql://localhost:3306/stock?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name:
    username: stock_admin
    password: stock
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      org:
        hibernate:
          format_sql: true
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        default_schema: stock
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    user: stock_admin
    password: stock
    enabled: true
    url: jdbc:mysql://localhost:3306/stock?serverTimezone=UTC&characterEncoding=UTF-8
    locations: classpath:db/migration, classpath:db/seed
    repeatable-sql-migration-prefix: R
    schemas: stock
  data:
    redis:
      host: localhost
      port: 6379
