version: '3'

networks:
  network:

volumes:
  stock-mysql:
  stock-redis:

services:
  mysql:
    container_name: stock-mysql
    image: ubuntu/mysql:edge
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1 --init-file /data/application/init.sql
    environment:
      - MYSQL_DATABASE=stock
      - MYSQL_USER=stock_admin
      - MYSQL_PASSWORD=stock
      - MYSQL_ROOT_PASSWORD=stock
      - TZ=UTC
    volumes:
      - stock-mysql:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
  redis:
    container_name: stock-redis
    image: redis:4-alpine
    networks:
      - network
    ports:
      - "6379:6379"
    volumes:
      - stock-redis:/data
